[[CUDA_compat]]
arch = "x86_64"
git-tree-sha1 = "b5e755e06f4d49a5ab1a638eea5d75bf20c66e3d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_compat.download]]
    sha256 = "a6cd6aa5c0ceb95e2d14064e012ecfd81e2ea1104612a7e0aec1ddabe59c153b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl/releases/download/CUDA_compat-v11.8.0+2/CUDA_compat.v11.8.0.x86_64-linux-gnu.tar.gz"
[[CUDA_compat]]
arch = "powerpc64le"
git-tree-sha1 = "7b4d06d1a0ff9386810fdf729b067d8ba77c97b5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_compat.download]]
    sha256 = "c732d8d14860892002d8e1f492deb6cdce899bdf934d89c09b2f3e7bb5414a7e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl/releases/download/CUDA_compat-v11.8.0+2/CUDA_compat.v11.8.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_compat]]
arch = "aarch64"
git-tree-sha1 = "6775921ab78b370d8da50fb0b79e1cff0baa94b9"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_compat.download]]
    sha256 = "2bbf905872c1d57d076c74aae9f7f57ecd2525ca3b36386eee8fbc18ca71dd7a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl/releases/download/CUDA_compat-v11.8.0+2/CUDA_compat.v11.8.0.aarch64-linux-gnu.tar.gz"
