# Autogenerated wrapper script for CUDA_compat_jll for x86_64-linux-gnu-cuda+11.4
export libcuda, libnvidia_ptxjitcompiler

JLLWrappers.@generate_wrapper_header("CUDA_compat")
JLLWrappers.@declare_library_product(libcuda, "libcuda.so.1")
JLLWrappers.@declare_library_product(libnvidia_ptxjitcompiler, "libnvidia-ptxjitcompiler.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcuda,
        "lib/libcuda.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvidia_ptxjitcompiler,
        "lib/libnvidia-ptxjitcompiler.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
